version: "3.0"

services:
  sample:
    container_name: casanova
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    stdin_open: true